// import 'package:flutter/material.dart';

// ignore_for_file: constant_identifier_names

const String DubaiAirport = "Dubai Airport - DXB";
const String Dubai = "Dubai";
const String UnitedArabEmirates = "United Arab Emirates";
const String temp = "19 C";
const String cloudy = "Cloudy";
const String date = "30 Jan";
const String Mon = "Mon";
const String time = "8:45 PM";
const String timezone = "GMT +4";
const String currency = "AED";
const String conversion = "1\$ =  3.67AED";
const String getDirection = "Get direction";
const String callAirport = "Call airport";
const String transport = "Transport";
const String terminal = "Terminal";
const String forex = "Forex";
const String contact_info = "Contact info";
const String taxi_service = "Taxi Service";
const String public_transport = "Public transport";
const String metro = "Metro";
const String metro_time = "6am - 10pm";
const String bus = "Bus";
const String busTime = "available 24hrs";
const String self_parking = "Self parking";
const String t1 = "T1";
const String t2  = "T2";
const String t3  = "T3";
const String two_wheeler = "Two wheeler";
const String car_parking = "Car Parking";
const String electric_car_parking = "Electric Car Parking";
const String fiftypd = "AED 50 / day";
const String hundredpd = "AED 100 / day";
const String terminal_map = "Terminal Map";
const String view = "View";
const String foreignexchange  = "Foreign Exchange";
const String travelex = "Travelex";
const String terminal3 = "Terminal 3-";
const String airside =  "Airside Dept Downtown, Concourse B,";
const String winston = "Terminal 3, beside Winston Smoking room";
const String alansari = "Al Ansari Exchange";
const String emirates = "Emirates NBD";
const String contact = "Contact Airport";
const String police = "Police";
const String lostandfound = "Lost and Found";
const String headOffice = "Head Office";
